### ISSUE TITLE
Improvements to packaging effort

### ISSUE THREAD

**Issue by rufuspollock** [uwaheed88/united-states-historical-house-prices#3]
* [x] Avoid upper case file names if possible ... 
* [x] Ugly titling of package `Historical us house prices` (US is surely capitalized) 
* [x] No description in README or (more importantly) datapackage.json of what the different files contain (what is Real-Building-Cost-Index)
* [x] No clear statement of where data came from or who created it
* [x] Licensing statement does not make sense (why would it being a US company make this public domain?) - have you looked at source website to see what it says?
* [x] Why did you remove columns like "U.S. Population Millions", "Long Rate", "HPI Source", "Nominal Building Cost Index", "CPI Annual & Quarterly", "CPI Annual"?

**Comment by uwaheed88** [comment]
FIXED. Implemented this feedbacks. See commit https://github.com/uwaheed88/united-states-historical-house-prices/commit/e859810431b762f86d25240a8cfece7b46ad0deb
