### ISSUE TITLE
Dates are floats or fractions rather than yyyy-mm 

### ISSUE THREAD

**Issue by rufuspollock** [uwaheed88/united-states-historical-house-prices#4]
`1890.0` vs `1890`
`1965.625` vs `1965-05`

**Comment by rufuspollock** [comment]
@uwaheed88 when closing can you leave an informative comment as per http://handbook.datopian.com/issues-tasks/

**Comment by uwaheed88** [comment]
FIXED. Converted the "Date" field from float to date. See commit https://github.com/uwaheed88/united-states-historical-house-prices/commit/90ddfa57c0646ef4ce27055dec271bf6267ed9e6
