### ISSUE TITLE
Why split data into 4 separate data series

### ISSUE THREAD

**Issue by rufuspollock** [uwaheed88/united-states-historical-house-prices#6]
I was not clear why we split into 4 separate sheets vs one original. maybe there is a good reason but explanation would be useful

**Comment by uwaheed88** [comment]
FIXED. Keeping all the fields in a single CSV. See commit https://github.com/uwaheed88/united-states-historical-house-prices/commit/90ddfa57c0646ef4ce27055dec271bf6267ed9e6
