### ISSUE TITLE
Pandas seems like overkill

### ISSUE THREAD

**Issue by rufuspollock** [uwaheed88/united-states-historical-house-prices#7]
You are using pandas to read an excel, skip a few rows and then subselect. This seems overkill. It also leads to odd typing issues that may be source of other issues e.g. #4

**Comment by uwaheed88** [comment]
FIXED. Shifted the script to use "xlrd" for parsing purposes. See commit https://github.com/uwaheed88/united-states-historical-house-prices/commit/90ddfa57c0646ef4ce27055dec271bf6267ed9e6
